users = [{"username": "s77518",
        "state": "ACCESS_APPROVED",
        "approval_id": 123,
        "answered_by": "Kuchen",
        "portal_groups": "Kakatoo",
        "service_account": "default",
        },
        {"username": "s12345",
        "state": "NEW",
        "approval_id": 456,
        "answered_by": "Großer Kuchen",
        "portal_groups": "Mandarine",
        "service_account": "default",
        }]

webapps = [{"name": "kakatoo",
            "link_show": "false",
            "link_name": "kuchen",
            "link_url": "https://mango.com",
            "oidc_client": "Kikeriki",
            "can_subauth": "true",
            }]

metrics = [{"Kubernetes": "v1.15.4"},
           {"API Server": "https://10.96.0.1:443"},
           {"Cluster Nodes": 24},
           {"CPU Cores": 1536},
           {"Main Memory": "12543.876796Gi"},
           {"Deployed Pods": 723},
           {"Allocated Volumes": 227},
           {"Portal Users": 120},
           {"KubePortal": "v.0.3.16"},
           ]
